### ISSUE TITLE
MIxup in zaws login profiles

### ISSUE THREAD

**Issue by amitrangra** [zalando-stups/planb-cassandra#184]
Steps followed:
1. zaws login foundation PowerUser
2. ./planb.py update
3. First instance got terminated and restarted
4.  Before moving to the script gave the following exception:
    botocore.exceptions.ProfileNotFound: The config profile (planb_autorecovery) could not be found
5. zaws login foundation PowerUser --awsprofile planb_autorecovery
6. ./planb.py update threw the following exception:
   botocore.exceptions.NoCredentialsError: Unable to locate credentials
7. zaws login foundation PowerUser, so that we now have default and planb_autorecovery in aws/credentials
8. ./planb.py update, worked

**Comment by a1exsh** [comment]
This is not the way it is supposed to work.  Please follow the instructions on setting up your environment here: https://github.com/zalando/planb-cassandra#prerequisites

**Comment by a1exsh** [comment]
I think this is resolved.
