### ISSUE TITLE
Update cassandra scalyr region

### ISSUE THREAD

**Issue by zaynetro** [zalando-stups/planb-cassandra#194]
Hi, we are trying to update scalyr region to EU for our cassandra cluster.

We ran:

```
./planb.py update --cluster-name bling-cassandra-staging \
    --docker-image registry.opensource.zalan.do/bling/movmnt-cassandra-2:cd7 \
    --region eu-central-1 \
    --force-termination \
    --scalyr-region eu \
    -O odd-eu-central-1.bling.zalan.do
```

And it successfully updated our cassandra instance. Unfortunately, updated instance didn't start sending logs to EU region.

How to debug the scalyr region? Where is scalyr_region being set on the instance? Can we use update to change scalyr region?

**Comment by a1exsh** [comment]
This looks like a general STUPS/AWS question to me.

**Comment by a1exsh** [comment]
Following up on a more suitable channel.

**Comment by zaynetro** [comment]
Could you suggest a more suitable channel?

**Comment by zaynetro** [comment]
OK. The problem was outdated taupage :man_facepalming:
