### ISSUE TITLE
Run remote command host specific

### ISSUE THREAD

**Issue by vibhory2j** [zalando-stups/planb-cassandra#225]
It would be nice to also run the remote command specific to some hosts in the cluster.

**Comment by a1exsh** [comment]
@vibhory2j Yeah, that should be possible.  Do you mean specific IP address or specific rack?  Just in case, maybe worth looking at what cstar does for inspiration: https://github.com/spotify/cstar

**Comment by a1exsh** [comment]
You can now use `--filters` to specify either a single host (with `private-ip-address` filter) or groups of hosts, e.g. per Availability Zone.
