### ISSUE TITLE
Support adding more nodes (or regions) to existing cluster

### ISSUE THREAD

**Issue by a1exsh** [zalando-stups/planb-cassandra#23]
The cluster management script should provide the commands to add (or remove) nodes in an already running cluster, as well as adding a new region (or decommissioning an old one).

This task will benefit from some refactoring of the `create-cluster.py` script.

**Comment by Jan-M** [comment]
:+1: for this

**Comment by a1exsh** [comment]
Note to implementors: the replication factors of `system_auth` keyspace should be increased before adding a new node, otherwise the clients won't be able to connect to it due to missing credentials on the server side.

**Comment by a1exsh** [comment]
The algorithm for adding new node(s) should be something like this:
- allocate the required private/public IP address(es) for new node(s)
- update security group in case of multi-region setup (how do we know, btw?)
- launch new node instance(s) with the same user data (fetch it from one of the already running nodes)
- wait for new node to bootstrap (this might be tricky, for initial bootstrap we've had a fixed timeout, but here we need some actual nodetool-like status check)
- update SRV record

**Comment by a1exsh** [comment]
And in order to update `system_auth` repl. factor we'd need to open an SSH tunnel using piu, then ssh to run cql command from inside docker...

**Comment by Jan-M** [comment]
To my understanding the step of changing replication factor of auth could be ignored at first

**Comment by a1exsh** [comment]
@Jan-M if you can make sure that no new clients try to connect at the time you're scaling up, then yes.

**Comment by Jan-M** [comment]
Assuming you have a list of seed nodes as contact points isnt it safe to assume for that period of time the client will be able to reach some nodes?

**Comment by a1exsh** [comment]
We used to put all nodes as contact points, not only the seed ones, but this is not the point actually.  From a seed node or not, the client will try to reach the newly added node as soon as it is fully bootstrapped (and it has a query to run on that node), but the node won't have system_auth in place so it will reject the client's request based on 'invalid' credential.  Now that I think about it, this will affect not only the new clients, but the already running ones as well (they learn about new nodes becoming available due thanks to gossip).

**Comment by Jan-M** [comment]
That sounds like a circle?

**Comment by a1exsh** [comment]
No, because if you increase repl factor in advance, the node that bootstraps will pick responsibility for the extra replica. :-)  We've tested this part sometime ago.

**Comment by LappleApple** [comment]
Hey @a1exsh, can we close this issue? It dates back to April 2016. 

Or, we could add a "Help Wanted" label, if there's anything to do.

**Comment by a1exsh** [comment]
This is also in the plans for near future.

**Comment by LappleApple** [comment]
@a1exsh Can you add a "Help Wanted" label? Then maybe you'll get some help/contributors. It's public, after all. :)

**Comment by a1exsh** [comment]
Implemented in #164
